# MNIST DATASET

목표: 흑백 손글씨 이미지(0 ~ 9)를 0 ~ 9로 분류한다.

구성: 60000개의 훈련 이미지, 10000개의 테스트 이미지 cf.이미지와 레이블(그냥 수 배열로 구성)은 일대일 관계

In [1]:
from keras.datasets import mnist
(train_images,train_labels),(test_images,test_labels) = mnist.load_data()
#train_images,train_labels가 모델이 학습해야할 훈련 세트
#test_images,test_labels를 통하여 테스트할 것임
#이미지는 넘파이 배열로 인코딩되어 있으며 레이블(특정 샘플의 클래스)는 0~9까지의 숫자 배열
#cf.분류 문제의 범주(category): 클래스(class). 데이터 포인트: 샘플(sample). 특정 샘플의 클래스: 레이블(lable)

print(train_images.shape) #shape는 배열의 크기 출력(면,행,열)
print(len(train_labels)) 
print(train_labels)
print(test_labels)


(60000, 28, 28)
60000
[5 0 4 ... 5 6 8]
[7 2 1 ... 4 5 6]


In [2]:
from keras import models
from keras import layers

network = models.Sequential()
network.add(layers.Dense(512, activation='relu',input_shape=(28*28,))) 
                         #↖노드 개수:512, relu는 음수를 0으로 만든다, (28*28,):1차원으로 입력받음 
network.add(layers.Dense(10,activation='softmax')) #10개의 확률이 들어있는 배열을 반환. softmax는 총합이 1.

In [3]:
network.compile(optimizer='rmsprop', #옵티마이저(optimizer): 역전파 알고리즘을 구현한 함수, 손실함수를 기반으로 가중치 업데이트
               loss='categorical_crossentropy', #손실함수(loss function): 기대치에서 얼마나 벗어났는지 측정
               metrics=['accuracy'])

In [4]:
train_images = train_images.reshape((60000,28*28)) #행과 열을 하나의 배열로 묶음(60000,28,28) -> (60000,28*28)
train_images = train_images.astype('float32') / 255 #0~255 사이의 값을 가지는 배열을 0~1사이로 만듦(자료형 또한 uint8->float32)

test_images = test_images.reshape((10000,28*28))
test_images = test_images.astype('float32') / 255

In [5]:
#from keras.utils import to_categorical -> ImportError: cannot import name 'to_categorical' from 'keras.utils'
from tensorflow.keras.utils import to_categorical

train_labels = to_categorical(train_labels) #one-hot encoding 해줌
test_labels = to_categorical(test_labels)
print(train_labels)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [6]:
network.fit(train_images, train_labels, epochs=5, batch_size=128) #훈련 데이터에서 128개를 뽑아 훈련하는 과정을 5번 반복

Epoch 1/5
469/469 [==============================] - 3s 5ms/step - loss: 0.2627 - accuracy: 0.9251
Epoch 2/5
469/469 [==============================] - 2s 5ms/step - loss: 0.1056 - accuracy: 0.9690
Epoch 3/5
469/469 [==============================] - 2s 5ms/step - loss: 0.0698 - accuracy: 0.9793
Epoch 4/5
469/469 [==============================] - 2s 5ms/step - loss: 0.0504 - accuracy: 0.9846
Epoch 5/5
469/469 [==============================] - 2s 5ms/step - loss: 0.0376 - accuracy: 0.9885


In [7]:
test_loss, test_acc = network.evaluate(test_images, test_labels) #실행 결과 정확도가 소폭 감소한것은 overfitting 때문
print("손실:",test_loss)
print("정확도:",test_acc)

313/313 [==============================] - 0s 1ms/step - loss: 0.0678 - accuracy: 0.9798
손실: 0.06784217804670334
정확도: 0.9797999858856201
